#!/bin/bash
# Copyright 2022 The Chromium Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This script is meant to be run once to setup the example demo agent.
# Run it with one command line argument: the path to a directory where the
# demo agent will be built.  This should be a directory outside the SDK
# directory tree.  This directory must not already exist.
#
# Once the build is prepared, the demo binary is build using the command
# `cmake --build <build-dir>`, where <build-dir> is the same argument given
# to this script.

set -euo pipefail

export BUILD_DIR=$(realpath $1)
export ROOT_DIR=$(realpath $(dirname $0)/..)
export DEMO_DIR=$(realpath $ROOT_DIR/demo)
export PROTO_DIR=$(realpath  $ROOT_DIR/proto)

echo Root dir:   $ROOT_DIR
echo Build dir:  $BUILD_DIR
echo Demo dir:   $DEMO_DIR
echo Proto dir:  $PROTO_DIR

test -d $BUILD_DIR && (
  echo ""
  echo "  *** $BUILD_DIR must not exist"
  return 1 2>/dev/null || exit 1
)

mkdir -p $BUILD_DIR
cd $BUILD_DIR

# Install vcpkg and use it to install Google Protocol Buffers.
test -d vcpkg || (
  git clone https://github.com/microsoft/vcpkg
  ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
  ./vcpkg/vcpkg install protobuf
)

# Generate proto files.
mkdir -p gen
./vcpkg/installed/x64-linux/tools/protobuf/protoc \
  --cpp_out=gen \
  --proto_path=$PROTO_DIR \
  $PROTO_DIR/content_analysis/sdk/analysis.proto

# Generate the build files.
export CMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
cmake $DEMO_DIR

